
'use client'
import { useEffect, useState } from 'react'
import { Sparkles, FileText, BriefcaseBusiness, Loader2, Upload, History } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { analyzeJob, analyzeResume, JobAnalysis, ResumeAnalysis, uploadResume } from '@/services/ai-service'
import { AuthUser } from '@/services/auth-service'
import { apiRequest } from '@/services/api-client'
import { authService } from '@/services/auth-service'

export function AIAnalyzerPage({ user, mode = 'job' }: { user: AuthUser; mode?: 'job'|'resume' }) {
 const active=mode==='job'; const [text,setText]=useState(''); const [targetRole,setTargetRole]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [job,setJob]=useState<JobAnalysis|null>(null); const [resume,setResume]=useState<ResumeAnalysis|null>(null); const [history,setHistory]=useState<any[]>([]); const [fileName,setFileName]=useState('')
 useEffect(()=>{void apiRequest<{history:any[]}>('/ai/history',{headers:{Authorization:`Bearer ${authService.getCurrentUser()?.token}`}}).then(r=>setHistory((r.history||[]).filter((h:any)=>h.type===mode))).catch(()=>{})},[mode])
 const run=async()=>{if(!text.trim())return;setLoading(true);setError('');try{if(active){const r=await analyzeJob(text,targetRole);setJob(r.result)}else{const r=await analyzeResume(text,targetRole);setResume(r.result)}}catch(e){setError(e instanceof Error?e.message:'Analysis failed.')}finally{setLoading(false)}}
 const handleFile=async(file:File)=>{setLoading(true);setError('');setFileName(file.name);try{if(file.type==='text/plain'||file.name.endsWith('.txt')||file.name.endsWith('.md'))setText(await file.text());else {const r=await uploadResume(file);setText(r.resumeText)}}catch(e){setError(e instanceof Error?e.message:'Could not read resume file.')}finally{setLoading(false)}}
 const result=active?job:resume
 return <section className="space-y-6"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-indigo-50 px-3 py-1 text-[11px] font-semibold text-indigo-700 dark:bg-indigo-500/10 dark:text-indigo-300"><Sparkles size={13}/> AI-POWERED ANALYSIS</div><h2 className="text-2xl font-bold tracking-tight sm:text-3xl">{active?'Job Description Analyzer':'Resume Analyzer'}</h2><p className="mt-1 text-sm text-slate-500">{active?'Paste a real job description and compare it with your saved profile.':'Upload a PDF resume or paste resume text, then analyze it against your target role.'}</p></div>
 <div className="grid gap-5 xl:grid-cols-[1fr_1.15fr]"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="mb-4 flex items-center gap-2 font-semibold">{active?<BriefcaseBusiness size={17}/>:<FileText size={17}/>} {active?'Job Description':'Resume Input'}</div><input value={targetRole} onChange={e=>setTargetRole(e.target.value)} placeholder="Target role (optional)" className="mb-3 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-indigo-500 dark:border-slate-700 dark:bg-slate-800"/>{!active&&<label className="mb-3 flex cursor-pointer items-center justify-between rounded-2xl border border-dashed border-indigo-200 bg-indigo-50/60 p-4 dark:border-indigo-500/30 dark:bg-indigo-500/5"><div><p className="text-xs font-semibold text-indigo-700 dark:text-indigo-300">Upload resume</p><p className="mt-1 text-[10px] text-slate-500">PDF, TXT or Markdown</p>{fileName&&<p className="mt-1 text-[10px] font-medium text-emerald-600">{fileName} loaded</p>}</div><span className="grid size-9 place-items-center rounded-xl bg-white text-indigo-600 shadow-sm dark:bg-slate-800"><Upload size={16}/></span><input type="file" accept=".pdf,.txt,.md,text/plain,application/pdf" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void handleFile(f)}}/></label>}<textarea value={text} onChange={e=>setText(e.target.value)} rows={18} placeholder={active?'Paste the complete job description here...':'Paste the text of your resume here or upload a PDF above...'} className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm leading-relaxed outline-none focus:border-indigo-500 dark:border-slate-700 dark:bg-slate-800"/><Button onClick={run} disabled={loading||!text.trim()} className="mt-3 w-full rounded-xl bg-indigo-600 hover:bg-indigo-700">{loading?<><Loader2 className="animate-spin"/>Analyzing...</>:<><Sparkles/>Analyze with AI</>}</Button>{error&&<p className="mt-3 rounded-xl bg-rose-50 p-3 text-xs text-rose-700">{error}</p>}</div>
 <div className="space-y-4"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">{!result?<div className="grid min-h-[500px] place-items-center text-center text-sm text-slate-400"><div><Sparkles className="mx-auto mb-3" size={30}/><p>Your analysis will appear here.</p><p className="mt-1 text-xs">Results are saved to your private AI history.</p></div></div>:active?<JobResult result={job!}/>:<ResumeResult result={resume!}/>}</div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2"><History size={16}/><h3 className="text-sm font-semibold">Recent {active?'job':'resume'} analyses</h3></div><div className="mt-3 space-y-2">{history.slice(0,5).map((h:any,i:number)=><div key={i} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><span className="text-xs font-medium">{new Date(h.createdAt).toLocaleString()}</span><span className="text-[10px] font-semibold text-indigo-600">Saved</span></div>)}{!history.length&&<p className="text-xs text-slate-400">No previous analyses yet.</p>}</div></div></div></div></section>
}
function JobResult({result}:{result:JobAnalysis}){return <div className="space-y-5"><div className="flex items-center justify-between"><div><p className="text-xs text-slate-400">Role</p><h3 className="font-bold">{result.role}</h3></div><div className="text-right"><p className="text-3xl font-bold text-indigo-600">{result.matchPercentage}%</p><p className="text-[10px] text-slate-400">skill match</p></div></div><p className="text-sm leading-relaxed text-slate-600 dark:text-slate-300">{result.summary}</p><Panel title="Strong skills"><Tags items={result.strongSkills}/></Panel><Panel title="Missing / priority gaps"><div className="space-y-2">{result.missingSkills.map((x,i)=><div key={i} className="rounded-xl border border-slate-100 p-3 dark:border-slate-800"><div className="flex justify-between gap-3"><b className="text-sm">{x.skill}</b><span className="text-[10px] font-semibold text-amber-600">{x.importance}</span></div><p className="mt-1 text-xs text-slate-500">{x.why}</p></div>)}</div></Panel><Panel title="Action plan"><ul className="space-y-2 text-sm">{result.actionPlan.map((x,i)=><li key={i} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><b>{x.skill}:</b> {x.action}</li>)}</ul></Panel></div>}
function ResumeResult({result}:{result:ResumeAnalysis}){return <div className="space-y-5"><div className="grid grid-cols-2 gap-3"><Score label="Role alignment" value={result.roleAlignmentPercentage}/><Score label="Skill coverage" value={result.skillCoveragePercentage}/></div><p className="text-sm leading-relaxed text-slate-600 dark:text-slate-300">{result.summary}</p><Panel title="Detected skills"><Tags items={result.detectedSkills}/></Panel><Panel title="Strengths"><List items={result.strengths}/></Panel><Panel title="Improvements"><List items={result.improvements}/></Panel><Panel title="Action items"><List items={result.actionItems}/></Panel>{result.projects.length>0&&<Panel title="Detected projects"><List items={result.projects.map(p=>`${p.name} — ${p.technologies.join(', ')}`)}/></Panel>}</div>}
function Score({label,value}:{label:string,value:number}){return <div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-2xl font-bold text-indigo-600">{value}%</p></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div><h4 className="mb-2 text-sm font-semibold">{title}</h4>{children}</div>}
function Tags({items}:{items:string[]}){return items.length?<div className="flex flex-wrap gap-2">{items.map(x=><span key={x} className="rounded-full bg-indigo-50 px-2.5 py-1 text-[11px] font-semibold text-indigo-700 dark:bg-indigo-500/10 dark:text-indigo-300">{x}</span>)}</div>:<p className="text-xs text-slate-400">None detected.</p>}
function List({items}:{items:string[]}){return items.length?<ul className="space-y-2 text-sm text-slate-600 dark:text-slate-300">{items.map((x,i)=><li key={i} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800">{x}</li>)}</ul>:<p className="text-xs text-slate-400">None.</p>}
