'use client'
import { useEffect, useState } from 'react'
import { BrainCircuit, Loader2, Route, Target, Sparkles, History } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { AuthUser } from '@/services/auth-service'
import { getTargetRole, getUserSkills } from '@/services/user-data-service'
import { generateRoadmap, generateSkillGap } from '@/services/ai-service'
import { apiRequest } from '@/services/api-client'
import { authService } from '@/services/auth-service'

export function AICareerCoachPage({user}:{user:AuthUser}){
 const [role,setRole]=useState('Software Developer'); const [skills,setSkills]=useState<any[]>([]); const [gap,setGap]=useState<any>(null); const [roadmap,setRoadmap]=useState<any>(null); const [loading,setLoading]=useState(''); const [coach,setCoach]=useState<any>(null); const [history,setHistory]=useState<any[]>([])
 useEffect(()=>{void Promise.all([getTargetRole(user.id),getUserSkills(user.id)]).then(([r,s])=>{setRole(r);setSkills(s)}); void apiRequest<{history:any[]}>('/ai/history',{headers:{Authorization:`Bearer ${authService.getCurrentUser()?.token}`}}).then(r=>setHistory(r.history||[])).catch(()=>{})},[user.id])
 const runGap=async()=>{setLoading('gap');try{setGap((await generateSkillGap(role,skills)).result)}finally{setLoading('')}}
 const runRoadmap=async()=>{setLoading('roadmap');try{setRoadmap((await generateRoadmap(role,skills,gap?.gaps||[])).result)}finally{setLoading('')}}
 const runCoach=async()=>{setLoading('coach');try{const r=await apiRequest<{result:any}>('/ai/career-coach',{method:'POST',headers:{Authorization:`Bearer ${authService.getCurrentUser()?.token}`},body:JSON.stringify({targetRole:role,skills,gaps:gap?.gaps||[]})});setCoach(r.result)}finally{setLoading('')}}
 return <section className="space-y-6"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-indigo-50 px-3 py-1 text-[11px] font-semibold text-indigo-700"><BrainCircuit size={13}/> AI CAREER COACH</div><h2 className="text-2xl font-bold tracking-tight sm:text-3xl">AI Skill Analysis & Roadmap</h2><p className="mt-1 text-sm text-slate-500">Generate an AI analysis from your saved skills and target role, then turn the gaps into an ordered learning plan.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-slate-400">Current target role</p><p className="mt-1 text-lg font-bold">{role}</p><p className="mt-1 text-xs text-slate-500">{skills.length} saved skills available to the AI.</p></div><div className="flex flex-wrap gap-2"><Button onClick={runCoach} disabled={!!loading} variant="outline" className="rounded-xl">{loading==='coach'?<Loader2 className="animate-spin"/>:<Sparkles/>}What should I do today?</Button><Button onClick={runGap} disabled={!!loading} className="rounded-xl">{loading==='gap'?<Loader2 className="animate-spin"/>:<Target/>}Analyze skill gaps</Button><Button onClick={runRoadmap} disabled={!!loading||!gap} variant="outline" className="rounded-xl">{loading==='roadmap'?<Loader2 className="animate-spin"/>:<Route/>}Generate roadmap</Button></div></div></div>
 {coach&&<section className="rounded-2xl border border-indigo-100 bg-gradient-to-br from-indigo-50 via-white to-violet-50 p-5 shadow-sm dark:border-indigo-500/20 dark:from-indigo-500/10 dark:via-slate-900 dark:to-violet-500/10"><div className="flex items-center gap-2"><Sparkles className="text-indigo-600" size={18}/><h3 className="font-semibold">Today&apos;s AI focus</h3></div><p className="mt-3 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{coach.summary}</p><div className="mt-4 grid gap-3 md:grid-cols-3">{(coach.actions||[]).map((a:any,i:number)=><div key={i} className="rounded-xl border border-white/70 bg-white/80 p-4 dark:border-slate-700 dark:bg-slate-900/70"><p className="text-xs font-bold text-indigo-600">{i+1}. {a.title}</p><p className="mt-1 text-xs text-slate-500">{a.action}</p><p className="mt-2 text-[10px] font-semibold text-slate-400">{a.duration}</p></div>)}</div></section>}
 {gap&&<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><h3 className="font-semibold">AI Skill Gap Analysis</h3><span className="text-2xl font-bold text-indigo-600">{gap.overallMatchPercentage}%</span></div><div className="mt-4 grid gap-3 md:grid-cols-2">{(gap.gaps||[]).map((g:any,i:number)=><div key={i} className="rounded-xl border border-slate-100 p-4 dark:border-slate-800"><div className="flex justify-between gap-2"><b className="text-sm">{g.skill}</b><span className="text-[10px] font-semibold text-amber-600">{g.priority}</span></div><p className="mt-1 text-xs text-slate-500">{g.currentLevel} → {g.targetLevel}</p><p className="mt-2 text-xs leading-relaxed text-slate-500">{g.reason}</p><p className="mt-2 text-xs font-medium text-indigo-600">Next: {g.nextAction}</p></div>)}</div></section>}
 {roadmap&&<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><div><h3 className="font-semibold">AI-Generated Roadmap</h3><p className="mt-1 text-xs text-slate-500">Estimated {roadmap.estimatedWeeks} weeks</p></div></div><div className="mt-5 space-y-3">{(roadmap.steps||[]).map((s:any,i:number)=><div key={s.id||i} className="flex gap-4 rounded-xl border border-slate-100 p-4 dark:border-slate-800"><div className="grid size-8 shrink-0 place-items-center rounded-full bg-indigo-50 text-xs font-bold text-indigo-700">{i+1}</div><div className="flex-1"><div className="flex flex-wrap justify-between gap-2"><b className="text-sm">{s.title}</b><span className="text-[10px] font-semibold text-slate-400">{s.estimatedHours} hrs</span></div><p className="mt-1 text-xs text-slate-500">{s.description}</p><p className="mt-2 text-xs font-medium">Practice: <span className="font-normal text-slate-500">{s.practiceTask}</span></p></div></div>)}</div></section>}
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2"><History size={17}/><h3 className="font-semibold">Recent AI analyses</h3></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{history.slice(0,6).map((h:any,i:number)=><div key={i} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p className="text-xs font-semibold capitalize">{String(h.type||'analysis').replace('-', ' ')}</p><p className="mt-1 text-[10px] text-slate-400">{h.createdAt ? new Date(h.createdAt).toLocaleString() : 'Saved analysis'}</p></div>)}</div></section></section>
}
