
'use client'
import { useEffect, useState } from 'react'
import { Link, Save, UserRound } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { AuthUser } from '@/services/auth-service'
import { getProfile, saveProfile, ProfileData } from '@/services/profile-service'

export function ProfilePage({user}:{user:AuthUser}){
 const [form,setForm]=useState<ProfileData>({education:'B.Tech CSE (AI/ML)',college:'',graduationYear:'2027',github:'',linkedin:'',phone:'',bio:''}); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false)
 useEffect(()=>{void getProfile(user.id).then(setForm)},[user.id])
 const set=(k:keyof ProfileData,v:string)=>setForm(f=>({...f,[k]:v}))
 const submit=async()=>{setSaving(true);setSaved(false);try{await saveProfile(user.id,form);setSaved(true)}finally{setSaving(false)}}
 const completion=Math.round(Object.values(form).filter(v=>String(v).trim()).length/Object.keys(form).length*100)
 return <section className="space-y-6"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-indigo-50 px-3 py-1 text-[11px] font-semibold text-indigo-700 dark:bg-indigo-500/10 dark:text-indigo-300"><UserRound size={13}/> YOUR PROFILE</div><h2 className="text-2xl font-bold tracking-tight sm:text-3xl">Profile & Career Identity</h2><p className="mt-1 text-sm text-slate-500">Keep the information used by SkillPilot AI, its roadmap and dashboard accurate.</p></div>
 <div className="grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><div className="rounded-3xl border border-slate-200 bg-gradient-to-br from-indigo-600 via-violet-600 to-slate-900 p-6 text-white shadow-lg dark:border-slate-800"><div className="grid size-16 place-items-center rounded-2xl bg-white/15 text-xl font-bold backdrop-blur">{user.fullName.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><h3 className="mt-5 text-xl font-bold">{user.fullName}</h3><p className="mt-1 text-sm text-white/70">{user.email}</p><div className="mt-7"><div className="mb-2 flex justify-between text-xs text-white/70"><span>Profile completion</span><b className="text-white">{completion}%</b></div><div className="h-2 rounded-full bg-white/15"><div className="h-full rounded-full bg-white" style={{width:`${completion}%`}}/></div></div><div className="mt-7 space-y-2 text-xs text-white/75"><p>🎯 Target role is managed separately in Target Role.</p><p>🤖 AI uses your saved profile and skills as context.</p></div></div>
 <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="grid gap-4 sm:grid-cols-2">{([['education','Education'],['college','College / University'],['graduationYear','Graduation Year'],['phone','Phone'] ] as [keyof ProfileData,string][]).map(([k,l])=><label key={k} className="space-y-1.5"><span className="text-xs font-semibold text-slate-500">{l}</span><input value={form[k]} onChange={e=>set(k,e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10 dark:border-slate-700 dark:bg-slate-800" /></label>)}
 <label className="space-y-1.5"><span className="text-xs font-semibold text-slate-500">GitHub</span><div className="relative"><Link className="absolute left-3 top-3.5 size-4 text-slate-400"/><input value={form.github} onChange={e=>set('github',e.target.value)} placeholder="https://github.com/username" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-indigo-500 dark:border-slate-700 dark:bg-slate-800" /></div></label>
 <label className="space-y-1.5"><span className="text-xs font-semibold text-slate-500">LinkedIn</span><div className="relative"><Link className="absolute left-3 top-3.5 size-4 text-slate-400"/><input value={form.linkedin} onChange={e=>set('linkedin',e.target.value)} placeholder="https://linkedin.com/in/username" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-indigo-500 dark:border-slate-700 dark:bg-slate-800" /></div></label></div><label className="mt-4 block space-y-1.5"><span className="text-xs font-semibold text-slate-500">Short bio</span><textarea value={form.bio} onChange={e=>set('bio',e.target.value)} rows={4} placeholder="A concise summary of your current focus, strengths and career direction." className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-indigo-500 dark:border-slate-700 dark:bg-slate-800"/></label><div className="mt-5 flex items-center justify-end gap-3">{saved&&<span className="text-xs font-medium text-emerald-600">Profile saved</span>}<Button onClick={submit} disabled={saving} className="rounded-xl bg-indigo-600 hover:bg-indigo-700"><Save size={15}/>{saving?'Saving...':'Save profile'}</Button></div></div></div></section>
}
